# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: false
os:
  - linux
  - osx
latex: false
env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes"


