---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# orddid

<!-- badges: start -->
<!-- badges: end -->


+ Author: [Soichiro Yamauchi](https://soichiroy.github.io/)

+ For a detailed description of the method see: 

	Difference-in-Differences for Ordinal Outcome



## Installation Instructions 

You can install the released version of orddid from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("orddid")
```

And the development version from [GitHub](https://github.com/) with:

``` r
require("devtools")
install_github("soichiroy/orddid", dependencies=TRUE)
```
## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
## load package 
library(orddid)

## load example data 
data(gun_twowave)


## Estimate causal effects 
set.seed(1234)
fit <- ord_did(
  Ynew = gun_twowave$guns12,
  Yold = gun_twowave$guns10,
  treat = gun_twowave$treat_100mi,
  cut = c(0, 1),
  n_boot = 500,
  pre = FALSE,
  verbose = TRUE
)

## view summary 
summary(fit)
```

